image: python:3.6

stages:
  - deploy

.deploy_template: &deploy_template
  stage: deploy
  when: manual
  tags:
    - docker
  before_script:
    - pip install awscli
    - export AWS_DEFAULT_REGION="us-east-1"

deploy to dev:
  <<: *deploy_template
  environment:
    name: dev
  variables:
    env: dev
  script:
    - bash
    - layers=( "udl" "rdl" "fdl" "lrf" "prj" )
    - for layer in ${layers[@]}; do
    -   bash ddl_deploy.sh -e ${env} -l ${layer}
    - done
