DROP TABLE IF EXISTS deviceid;

CREATE EXTERNAL TABLE IF NOT EXISTS deviceid(item MAP<STRING, STRING>)
PARTITIONED BY (created DATE)
STORED AS PARQUET
LOCATION 's3://jornaya-dev-us-east-1-rdl/deviceid/';

MSCK REPAIR TABLE deviceid;
