DROP TABLE IF EXISTS urls;

CREATE EXTERNAL TABLE IF NOT EXISTS urls(item MAP<STRING, STRING>)
PARTITIONED BY (created DATE)
STORED AS PARQUET
LOCATION 's3://jornaya-dev-us-east-1-rdl/urls/'
TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY');

MSCK REPAIR TABLE urls;

