CREATE EXTERNAL TABLE IF NOT EXISTS `entities` (
  `code` VARCHAR(36)
, `name` VARCHAR(80)
, `insert_ts` TIMESTAMP
, `insert_job_run_id` VARCHAR(255)
, `source_ts` TIMESTAMP
)
STORED AS PARQUET
LOCATION '${LOCATION}'
TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY');
